### PR TITLE
Show uncovered code in the editor

### PR DESCRIPTION
**Pull request by lloiser**
using the `flow-ide` as an example 😁 

image

### CODE REVIEW

**Comment by steelbrain** [comment]
Great work @lloiser 

One thing I noticed was that coverage view responds to lint calls now instead of active pane item changed calls. It basically means that if you switch text editors and don't save in the new one, you'll still get coverage status for the old one.

You could fix it by adding a `WeakMap` and storing the results of each TextEditor tied to the TextEditor itself at the end of the lint call, and whenever the pane is changed, recalling those results and showing as appropriate, if the results are not found in the map, show unknown for text editors and reset for non-text-editors

How does it sound?

**Comment by lloiser** [comment]
:+1: I will give it try.

**Comment by steelbrain** [comment]
Thanks @lloiser 

This looks perfect 🆗

**Comment by rafaelcorreiapoli** [comment]
How can I disable this ?

**Comment by lloiser** [comment]
@rafaelcorreiapoli click the `Flow Coverage` in the status bar.

**Pull request merged**
